### ISSUE TITLE
安装依赖时提示没有需要版本的win32gui，也无法安装

### ISSUE THREAD

**Issue by younah0u0** [KroMiose/pjsk_auto_story#2]
[屏幕截图 2024-09-01 005138](https://github.com/user-attachments/assets/cb1ed61c-212a-4f21-a8b9-d60994db92ef)

**Comment by KroMiose** [comment]
把 requirements.txt 里面的 win32gui 版本改成 221.5 即可，但是该插件基于较早版本开发，实现原理是通过像素判断和坐标点击实现自动过剧情，游戏经过了多个版本更新，界面可能发生了改动，现在大概率是用不了的，需要根据现在的界面改动一些代码，如果非专业相关建议不要折腾了

**Comment by younah0u0** [comment]
好的谢谢大佬了

KroMiose ***@***.***> 于 2024年9月5日周四 21:09写道：
